version: '3.9'

services:
  web:
    build: .
    image: my-web-app
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:7.2-alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data: